version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOSTNAME=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fastapi
      - SECRET_KEY=f91ddda468f26afafee7af8851d735ad137ec41447a0b56824ede759e570a24f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  
  postgres:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: