name: Build and Deploy applicaion

on: [push, pull_request]

jobs:
  job1:
    env:
      DB_HOSTNAME: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: fastapi
      SECRET_KEY: f91ddda468f26afafee7af8851d735ad137ec41447a0b56824ede759e570a24f
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to koushik
        run: echo "Hello, Koushik!"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update Pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      


